/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "Achievement Gotten!": "成就达成!",
    "Inventory": "背包",
    "Locked": "未解锁",
    "Chests": "宝箱",
    "Potions": "药水",
    "Prestige": "声望",
    "permanent": "永久",
    "Index": "图鉴",
    "Search": "搜索",
    "Secret": "秘密",
    "Reset": "重置",
    "Quests": "任务",
    "Prestige Upgrades": "声望升级",
    "No items yet.": "暂无物品。",
    "SFX": "音效",
    "Shiny": "闪光",
    "Shop": "商店",
    "Zelda Fishing Idle": "塞尔达钓鱼放置",
    "Luck": "幸运",
    "Luck:": "幸运:",
    "Luck Potion": "幸运药水",
    "Music": "音乐",
    "Mythical": "神话",
    "Upgrades": "升级",
    "Unique": "独特",
    "tokens": "代币",
    "— they survive every prestige reset.": "- 每次转生重置均可保留（不受重置影响）",
    "[incrementaldb_verification: IdleHero503]": "[增量数据库校验：IdleHero503]",
    "[WARN] Inventory Full! Auto-Selling.": "[警告] 背包已满！自动出售中。",
    "+15% Luck for 30 minutes": "幸运值提升15%，持续30分钟",
    "+30% Reel Speed for 30 minutes": "收线速度提升30%，持续30分钟",
    "Catches": "垂钓捕获数",
    "Complete Reset": "完全重置",
    "Daily Quests": "每日任务",
    "Drew - Beta Tester": "Drew - 测试玩家",
    "Each spot has unique fish pools, slider speed, and rupee bonuses.": "每个垂钓点拥有专属鱼群、滑条速度和卢比加成。",
    "Earn Tokens by reaching Max Level and Casting Off.": "达到满级并放生可赚取代币。",
    "Fish caught:": "已捕获鱼类：",
    "Fish!": "钓鱼！",
    "Fishing": "钓鱼",
    "Fishing Spots": "钓点",
    "Lake Hylia": "海利亚湖",
    "MissZombae - Beta Tester": "MissZombae - 测试玩家",
    "New spots unlock as you level up — and beyond.": "升级后可解锁新垂钓点，满级后仍有后续解锁内容。",
    "Next: Coral Earring @ Lv5": "下一解锁：珊瑚耳环（5级解锁）",
    "Quick Sell All": "一键全部出售",
    "Quick Sell All (": "一键全部出售（",
    "Ready to fish!": "可以开始垂钓了！",
    "Reel Speed Potion": "收线速度药剂",
    "Reel:": "收线：",
    "These upgrades are": "这些升级",
    "Three quests reset every day at midnight. Complete them for Mon and Rupee bonuses.": "每日凌晨重置三个任务，完成可领取金币与卢比奖励。",
    "Triforce": "三神石",
    "Spots": "钓点",
    "it!": "它!",
    "5. SELL": "5. 出售",
    "[X] Missed the hook!": "[X] 错失咬钩时机！",
    "1. CAST": "1. 抛竿",
    "2. HOOK": "2. 提竿",
    "3. HOLD TO REEL": "3. 长按收线",
    "4. WATCH TENSION": "4. 留意张力值",
    "and wait.": "稍作等待。",
    "BITE! Hook it!": "鱼咬钩了！立刻提竿！",
    "Casting...": "抛竿...",
    "fish in your bag!": "鱼在你的背包里！",
    "HOOK!": "提竿！",
    "HOW TO FISH": "垂钓教程",
    "Let go": "松开手指",
    "Let's Fish!": "开始钓鱼！",
    "to drop.": "以。",
    "to progress.": "继续前进。",
    "Waiting for bite...": "等待鱼咬钩...",
    "[Unlocked] First Catch! +5 Mon": "[已解锁] 初次垂钓！获得5金币",
    "[X] Fish got away!": "[X] 鱼儿逃脱了！",
    "Catch Progress": "捕获进度",
    "Caught": "已捕获",
    "Hearty Bass": "暖心鲈鱼",
    "HOLD TO REEL": "长按进行收线",
    "Keep Tension in the middle to reel!": "保持张力在中间区间即可收线！",
    "Line Tension": "鱼线张力",
    "Rainbow! Lucky skies | +8% shiny rate for 5 casts": "天降祥瑞彩虹 | 接下来5次垂钓，稀有鱼概率+8%",
    "REELING...": "收线中...",
    "Sanke Carp": "锦鲤",
    "Stored in Bag!": "已存入背包！",
    "TOO HIGH!": "张力过高！",
    "TOO LOW!": "张力过低！",
    "Lucky Rod": "幸运鱼竿",
    "Magic Rod": "魔法鱼竿",
    "Max all upgrades": "最大全部升级",
    "Max out Luck": "满级运气",
    "a shiny fish": "捕捉一条 闪光 鱼",
    "[Shiny]": "[闪光]",
    "[Triforce]": "[三神石]",
    "[Quantity]": "[数量]",
    "[Upgrade]": "[升级]",
    "[Skill]": "[技能]",
    "[Lure]": "[诱饵]",
    "[ Active ]": "[ 激活 ]",
    "[Catch]": "[捕捉]",
    "-75 pulls to guaranteed shiny per tier.": "每层级累计75抽必出闪光品质。",
    "\"When the Calamity shook the foundations of Hyrule, the Triforce - scattered into eight shards by the Goddess Hylia's own design - sank into the kingdom's sacred waters to await a worthy angler.\"": "“当灾厄撼动海利亚大地根基之时，三角神力遵从海利亚女神的旨意碎裂为八块碎片，沉入王国的圣湖深水之中，静待有缘钓者现身。”",
    "Beedle's Wares": "比德尔杂货铺",
    "Quests reset in": "任务重置倒计时",
    "Angler Master": "垂钓大师",
    "Auto-Fish Owner": "自动垂钓特权",
    "Bait Beginner": "鱼饵新手",
    "Big Spender": "消费大亨",
    "Busy Beaver": "勤劳达人",
    "Collector": "收藏爱好者",
    "Epic Catch": "史诗渔获",
    "First Catch": "初次垂钓",
    "Fishing Frenzy": "垂钓狂潮",
    "Legendary Catch": "传说渔获",
    "Lifetime Angler": "资深钓客",
    "Lucky Angler": "幸运钓手",
    "Lure Master": "诱饵大师",
    "Lure Pro": "诱饵专家",
    "Mythical Catch": "神话渔获",
    "Perfect Hook": "完美提竿",
    "Prestige 1 + Lv30": "声望 1 + 30级",
    "Rare Catch": "稀有渔获",
    "Reel Speed Demon": "极速收线",
    "Secret Catch": "隐秘稀有渔获",
    "Shiny Collector": "闪光收藏者",
    "Shiny Hunter": "闪光猎人",
    "Shiny Master": "闪光宗师",
    "Shopaholic": "购物达人",
    "Triforce of Courage": "勇气三角神力",
    "Unique Catch": "独特渔获",
    "+15% XP gained per tier.": "每层级经验获取提升15%。",
    "+4% Rupees per fish per tier. Permanent.": "每层级每条鱼额外增加4%卢比，永久生效。",
    "+8% Rupees! (+0%)": "卢比加成+8%（基础加成0%）",
    "+Rupee bonus (Scales with Level)": "卢比加成（随等级增幅）",
    "A hidden pond deep in enchanted forest.": "魔法森林深处的隐秘池塘。",
    "A vast sun-drenched lake.": "一片日光充裕的辽阔大湖。",
    "An ancient electric sea.": "古老的雷电海域。",
    "Ancient Wisdom": "古老智慧",
    "Angler's Mark": "垂钓印记",
    "Auto Fish": "自动垂钓",
    "Big Chest": "大宝箱",
    "Bigger Bag": "更大背包",
    "Boss Chest": "首领宝箱",
    "Buy Auto Fish": "购买自动垂钓",
    "Can't Afford": "金币不足",
    "Catch a Legendary fish": "捕获一条传说鱼类",
    "Catch a Mythical fish": "捕获一条神话鱼类",
    "Catch a Rare fish": "捕获一条稀有鱼类",
    "Catch a Unique fish": "<捕获一条独特鱼类",
    "Catch all fish": "钓获所有鱼类",
    "Catch an Epic fish": "捕获一条史诗鱼类",
    "Catch the Secret fish": "捕获隐秘鱼类",
    "Catch your first fish": "钓获第一条鱼",
    "Catch your first shiny": "钓到第一条闪光鱼",
    "Collect all shards": "集齐所有碎片",
    "Crystal-clear rapids. No Common fish.": "澄澈清澈激流，无普通鱼类。",
    "Earn tokens EXCLUSIVELY by Prestiging.": "仅可通过转生获取代币。",
    "Fishes for you!": "鱼儿已上钩！",
    "Gilded Scale": "鎏金鳞片",
    "Guild Pass": "公会通行证",
    "Hold more fish! (Max 150)": "背包容量提升！上限150",
    "Lanayru Sea": "拉奈鲁之海",
    "Lost Woods Pond": "迷失森林池塘",
    "Max out Reel Speed": "收线速度升至满级",
    "No fish collected yet!": "尚未收集任何鱼类！",
    "No fish to sell!": "暂无可出售鱼类！",
    "No fish yet!": "还没有钓到鱼！",
    "Pity Stone": "保底之石",
    "Rewards: 100-600 Rupees": "奖励：100-600卢比",
    "Rewards: 20% Triforce | 40% Speed | 40% Mon": "奖励：三角神力碎片20% | 收线速度40% | 金币40%",
    "Rewards: 30% Luck | 20% Mon | 50% Rupees": "奖励：幸运值30% | 金币20% | 卢比50%",
    "Rupee Crystal": "卢比水晶",
    "Shiny fish faster! (Pity 350)": "更容易钓到闪光鱼！保底值350",
    "Shiny Magnet": "闪光磁石",
    "Small Chest": "小宝箱",
    "Strong Reel": "强力收线",
    "Unlock Coral Earring": "解锁珊瑚耳环",
    "Unlock Frog Lure": "解锁青蛙鱼饵",
    "Unlock Sinking Lure": "解锁沉水鱼饵",
    "Zora's Domain": "佐拉领地",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Shrine - Developer": "Shrine - 开发者",
    "Mythic": "神话",
    "Legendary": "传说",
    "Epic": "史诗",
    "Rare": "稀有",
    "Uncommon": "罕见",
    "Common": "普通",
    "SPD": "速度",
    "ATK": "攻击",
    "ARM": "护甲",
    "Lvl": "等级",
    "Unlock": "解锁",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "\xa0|\xa0": " | ",
    "—": "—",
    "•": "•",
    "−": "−",
    "×": "×",
    "←": "←",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "Next at ": "下一个在 ",
    "Starter Lure ": "新手诱饵 ", 
    "[Combo] ": "[连击] ",
    "[Streak] ": "[连杆] ",
    "[Water] Settled in ": "[水面] 水位稳定于 ",
    "[Locked] ": "[未解锁] ",
    "[Quest] ": "[任务] ",
    "Wait less time! ": "等待时间减少! ",
    "[Daily] ": "[日常] ",
    "Prestige Tokens: ": "声望代币：",
    "Reel faster & more Rupees! ": "收线更快、卢比收益更高！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)k$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^It took you (.+) to beat the game.$/, '你通关游戏用了 $1。'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^Rupees x([\d\.]+)$/, '卢比 x$1'],
    [/^Speed x([\d\.]+) \|$/, '速度 x$1 |'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^\+([\d\.]+)\% Reel$/, '+$1% 收线'],
    [/^\+([\d\.]+)\% Luck$/, '+$1% 幸运'],
    [/^\+([\d\.]+)\% Luck per tier.$/, '+$1% 幸运每级。'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) XP$/, '+$1 经验值'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) tokens$/, '$1 代币'],
    [/^([\d\.,]+) Mon$/, '$1 金币'],
    [/^Spend ([\d\.,]+) Mon$/, '花费 $1 金币'],
    [/^Spend ([\d\.,]+) rupees$/, '花费 $1 卢比'],
    [/^([\d\.,]+)x offline earnings rate.$/, '$1x 离线收益率。'],
    [/^Triforce Shard ([\d\.,]+)$/, '三神石碎片 $1'],
    [/^Catch ([\d\.,]+) Rare\+ fish$/, '捕捉 $1 稀有+ 鱼'],
    [/^Catch ([\d\.,]+) Legendary fish$/, '捕捉 $1 传说 鱼'],
    [/^Catch ([\d\.,]+) shinies$/, '捕捉 $1 闪光鱼'],
    [/^Catch ([\d\.,]+) different species$/, '捕捉 $1 不同的物种'],
    [/^Catch ([\d\.,]+) fish total$/, '总计捕捉 $1 鱼'],
    [/^Unlocks at Level ([\d\.,]+)$/, '解锁于 $1 级'],
    [/^Catch rare fish! \(([\d\.]+)\%\)$/, '捕捉稀有鱼! ($1%)'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^Lvl ([\d\.,]+)$/, '等级 $1'],
    [/^Hook ([\d\.,]+) fish perfectly$/, '成功钓到 $1 条鱼'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级: $1 \/ $2'],
    [/^Next: \+([\d\.]+)\% rupeeBonus$/, '下一级: +$1% 卢比加成'],
    [/^Next: \+([\d\.]+)\% xpBonus$/, '下一级: +$1% 经验加成'],
    [/^Next: \+([\d\.]+)\% luck$/, '下一级: +$1% 幸运'],
    [/^Next: \+([\d\.]+)\% shinyReduction$/, '下一级: +$1% 闪光削减'],
    [/^Next: \+([\d\.]+)\% offlineMult$/, '下一级: +$1% 离线乘数'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);